# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-09 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_learnerprogressnotification_assignment_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogressnotification',
            name='notification_event',
            field=models.CharField(blank=True, choices=[('Answered', 'Answered'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Help', 'HelpNeeded'), ('Promoted', 'Promoted'), ('Started', 'Started')], max_length=200),
        ),
        migrations.AlterField(
            model_name='learnerprogressnotification',
            name='notification_object',
            field=models.CharField(blank=True, choices=[('Help', 'Help'), ('Lesson', 'Lesson'), ('Promotion', 'Promotion'), ('Quiz', 'Quiz'), ('Resource', 'Resource')], max_length=200),
        ),
    ]
