# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.core.fields
import kolibri.utils.time_utils
import morango.models.fields.uuids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', morango.models.fields.uuids.UUIDField()),
                ('learner_name', models.CharField(max_length=200)),
                ('classroom_id', morango.models.fields.uuids.UUIDField()),
                ('facility_id', morango.models.fields.uuids.UUIDField()),
                ('quiz_id', morango.models.fields.uuids.UUIDField()),
                ('quiz_name', models.CharField(max_length=200)),
                ('quiz_score', models.IntegerField(null=True)),
                ('promotion_status', models.CharField(choices=[('REVIEW', 'Review'), ('RECOMMENDED', 'Recommended'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], max_length=100)),
                ('coach_approver', models.CharField(max_length=200, null=True)),
                ('admin_approver', models.CharField(max_length=200, null=True)),
                ('create_timestamp', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('update_timestamp', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
            ],
        ),
    ]
