# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionqueue',
            name='classroom_name',
            field=models.CharField(default='Math Class 3', max_length=100),
            preserve_default=False,
        ),
    ]
