# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-09 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotionqueue_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionqueue',
            name='lesson_completion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='promotionqueue',
            name='promotion_status',
            field=models.CharField(choices=[('LESSONS_PENDING', 'lessons_pending'), ('REVIEW', 'Review'), ('RECOMMENDED', 'Recommended'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], max_length=100),
        ),
    ]
