# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0019_collection_no_mptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitydataset',
            name='learner_promotion_required_lesson_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='facilitydataset',
            name='learner_promotion_required_quiz_score',
            field=models.FloatField(default=100.0),
        ),
    ]
