# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0020_auto_20211101_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityuser',
            name='physical_facility_grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
