# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-01 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0023_facilitydataset_allow_match_up_same_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitydataset',
            name='sort_match_up_by_physical_facility_level',
            field=models.BooleanField(default=True),
        ),
    ]
