# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 04:34
from __future__ import unicode_literals

from django.db import migrations
import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_usersessionlog_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='selected_question_ids',
            field=kolibri.core.fields.JSONField(blank=True, default=[]),
        ),
    ]
