# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import morango.models.fields.uuids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_interaction_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('amount_available', models.FloatField(default=0)),
                ('userType', models.CharField(choices=[('LEARNER', 'learner'), ('COACH', 'coach'), ('ADMIN', 'admin')], max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWageTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', morango.models.fields.uuids.UUIDField()),
                ('user_name', models.CharField(max_length=200)),
                ('created_timestamp', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('created_by_id', morango.models.fields.uuids.UUIDField()),
                ('created_by_name', models.CharField(max_length=200)),
                ('coach_approver_id', morango.models.fields.uuids.UUIDField()),
                ('coach_approver_name', models.CharField(max_length=200)),
                ('admin_approver_id', morango.models.fields.uuids.UUIDField()),
                ('admin_approver_name', models.CharField(max_length=200)),
                ('transaction_amount', models.FloatField(default=0)),
                ('before_balance', models.FloatField(default=0)),
                ('after_balance', models.FloatField(default=0)),
                ('request_type', models.CharField(choices=[('CREDIT', 'credit'), ('DEBIT', 'debit')], max_length=25)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('COACH_APPROVED', 'coach_approved'), ('COACH_DENIED', 'coach_denied'), ('COMPLETED', 'completed'), ('DENIED', 'denied')], max_length=25)),
            ],
        ),
    ]
