# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.core.fields
import kolibri.utils.time_utils
import morango.models.fields.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('wage_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwageaccount',
            name='last_interaction_timestamp',
            field=kolibri.core.fields.DateTimeTzField(blank=True, default=kolibri.utils.time_utils.local_now, null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='admin_approver_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='admin_approver_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='after_balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='coach_approver_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='coach_approver_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='created_timestamp',
            field=kolibri.core.fields.DateTimeTzField(blank=True, default=kolibri.utils.time_utils.local_now),
        ),
    ]
