# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        ('wage_tracker', '0002_auto_20211208_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwagetransactions',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, default=kolibri.utils.time_utils.local_now),
        ),
        migrations.AlterField(
            model_name='userwagetransactions',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('COACH_APPROVED', 'coach_approved'), ('COACH_DENIED', 'coach_denied'), ('COMPLETED', 'completed'), ('DENIED', 'denied'), ('DENIED_INSUFFICIENT_FUND', 'denied_insufficient_fund')], max_length=25),
        ),
    ]
