# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-11 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage_tracker', '0004_auto_20211211_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwagetransactions',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
