# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-16 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wage_tracker', '0005_userwagetransactions_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwageaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
