# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import morango.models.fields.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('match_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentee_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentee_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentor_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentor_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='supervisor_id',
            field=morango.models.fields.uuids.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='supervisor_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
