# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-31 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_up', '0004_auto_20211204_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupdetails',
            name='mentee_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT_SPECIFIED', 'Not specified'), ('DEFERRED', 'Defers for later')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='matchupdetails',
            name='mentee_physical_facility_level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='matchupdetails',
            name='mentor_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT_SPECIFIED', 'Not specified'), ('DEFERRED', 'Defers for later')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='matchupdetails',
            name='mentor_physical_facility_level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
