# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_up', '0005_auto_20211231_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentee_physical_facility_level',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matchupdetails',
            name='mentor_physical_facility_level',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
