# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_individualsyncableexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_pool_size',
            field=models.IntegerField(null=True),
        ),
    ]
